openapi: 3.0.0
servers:
  - url: "http://localhost:3000"
info:
  title: WASAText API
  description: API per WASAText
  version: 1.0.0

paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      operationId: doLogin
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  minLength: 3
                  maxLength: 16
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "abcdef012345"

  /users:
    get:
      tags: ["users"]
      summary: Cerca o elenca utenti
      operationId: searchUsers
      security:
        - BearerAuth: []
      parameters:
        - name: username
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Lista utenti restituita
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
                      description: username dell'utente
                    proPic:
                      type: string
                      description: foto profilo dell'utente

  /users/me/name:
    put:
      tags: ["users"]
      summary: Aggiorna il nome utente
      operationId: setMyUserName
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 16
              required:
                - name
      responses:
        '204':
          description: Nome aggiornato con successo
        '400': 
          $ref: "#/components/responses/BadRequest"

  /users/me/propic:
    put:
      tags: ["users"]
      summary: cambia foto profilo
      operationId: setMyPhoto
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                picture:
                  type: string
              required:
                - picture
      responses:
        '204':
          description: Foto aggiornata

  /conversations:
    get:
      tags: ["conversations"]
      summary: ricevi lista di conversazioni
      operationId: getMyConversations
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Conversazioni ritornate con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: id della conversazione (ID utente o ID gruppo)
                    name:
                      type: string
                      description: nome della conversazione (altro utente o gruppo)
                    picture:
                      type: string
                    lastMessageDate:
                      type: string
                      format: date-time
                    lastMessagePreview:
                      type: string
                    isGroup:
                      type: boolean
    post:
      tags: ["conversations"]
      summary: crea o recupera una chat diretta con un utente
      operationId: createConversation
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: l'username dell'utente con cui avviare la chat
              required:
                - username
      responses:
        '201':
          description: Conversazione creata o già esistente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: L'ID della conversazione

  /conversations/{id}/messages:
    get:
      tags: ["messages"]
      summary: Ottieni tutti i messaggi di una conversazione
      operationId: getConversation
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Messaggi restituiti
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user:
                      type: string
                    conversation:
                      type: integer
                    timestamp:
                      type: string
                      format: date-time
                    content:
                      type: string
                    isImage:
                      type: boolean
                    isForwarded:
                      type: boolean
                    isAnswer:
                      type: boolean
                    answerTo:
                      type: integer
                    isDeleted:
                      type: boolean
                    state:
                      type: string
                      enum:
                      - sent
                      - received
                      - read
                    reactions:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          user:
                            type: string
                          content:
                            type: string
                            description: emoji usata per la reazione
                            example: "👍"
                            minLength: 1
                            maxLength: 8



                  

                  

    post:
      tags: ["messages"]
      summary: Invia un messaggio
      operationId: sendMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                isImage:
                  type: boolean
                replyTo:
                  type: integer
                  description: ID del messaggio a cui si sta rispondendo
              required:
                - content
      responses:
        '201':
          description: Messaggio inviato
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: id del messaggio generato

  /conversations/{id}/messages/forward:
    post:
      tags: ["messages"]
      summary: Inoltra un messaggio esistente in questa conversazione
      operationId: forwardMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                messageId:
                  type: integer
                  description: L'ID del messaggio originale da inoltrare
              required:
                - messageId
      responses:
        '201':
          description: Messaggio inoltrato
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: id del messaggio inoltrato

  /messages/{id}:
    delete:
      tags: ["messages"]
      summary: Elimina un messaggio
      operationId: deleteMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Messaggio eliminato

  /messages/{id}/reactions:
    put:
      tags: ["messages"]
      summary: Aggiungi una reazione a un messaggio
      operationId: commentMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emoji:
                  type: string
              required:
                - emoji
      responses:
        '204':
          description: Reazione aggiunta
    delete:
      tags: ["messages"]
      summary: Rimuovi la reazione dal messaggio
      operationId: uncommentMessage
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Reazione rimossa

  /groups:
    post:
      tags: ["groups"]
      summary: Crea un nuovo gruppo
      operationId: createGroup
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                members:
                  type: array
                  items:
                    type: string
              required:
                - name
      responses:
        '201':
          description: Gruppo creato
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: id del gruppo creato

  /groups/{id}/name:
    put:
      tags: ["groups"]
      summary: Imposta nome del gruppo
      operationId: setGroupName
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '204':
          description: Nome aggiornato

  /groups/{id}/photo:
    put:
      tags: ["groups"]
      summary: Imposta foto del gruppo
      operationId: setGroupPhoto
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                picture:
                  type: string
              required:
                - picture
      responses:
        '204':
          description: Foto aggiornata

  /groups/{id}/members:
    post:
      tags: ["groups"]
      summary: Aggiungi un utente al gruppo
      operationId: addToGroup
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '204':
          description: Utente aggiunto

  /groups/{id}/members/me:
    delete:
      tags: ["groups"]
      summary: Abbandona il gruppo
      operationId: leaveGroup
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Uscito dal gruppo con successo

components:
  schemas:
    StatusInfo:
      title: Status Info
      type: object
      properties:
        status:
          type: string
          enum:
            - info
            - warning
            - critical
            - ""
        title: { type: string }
        message: { type: string }
        url: { type: string }

  responses:
    Unauthorized:
      description: The access token is missing or it's expired
    BadRequest:
      description: The request was not compliant with the documentation (eg. missing fields, etc)
    InternalServerError:
      description: The server encountered an internal error. Further info in server logs

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  parameters:
    XAppVersion:
      schema:
        type: string
        pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
        minLength: 1
        maxLength: 10
      name: X-App-Version
      in: header
      required: true
      description: App human readable version ("semantic version" format)
      allowEmptyValue: false
    XAppBuild:
      schema: { type: integer }
      name: X-App-Build
      in: header
      required: true
      description: App build number
      allowEmptyValue: false
    XAppLanguage:
      schema:
        type: string
        pattern: '^[a-z]{2}([-_][A-Z]{2})?$'
        minLength: 2
        maxLength: 5
      name: X-App-Language
      in: header
      required: true
      description: App language in ISO 639-1 format
      allowEmptyValue: false
    XAppPlatform:
      schema:
        type: string
        enum: [ios, android]
      name: X-App-Platform
      in: header
      required: true
      description: App operating system / platform
      allowEmptyValue: false
    cat:
      schema:
        type: string
        pattern: '^[a-zA-Z]+$'
        minLength: 3
        maxLength: 10
      name: cat
      in: path
      required: true
      description: Cat
      allowEmptyValue: false
